### ISSUE TITLE
希望可以增加BackdropVisualEffectView  代码生成视图模糊化

### ISSUE THREAD

**Issue by Xiaolangs** [goweii/maven-repository#1]
使用代码创建的视图  模糊不生效 

        val backdropVisualEffectView =BackdropVisualEffectView(this,null,0)
        backdropVisualEffectView.simpleSize = 4.32f
        val visualEffect: VisualEffect = RSBlurEffect(this, 25f)
        backdropVisualEffectView.visualEffect = visualEffect

**Comment by goweii** [comment]
用的哪个版本的？

**Comment by Xiaolangs** [comment]
> 用的哪个版本的？

最新版的   用代码生成的布局  这个都会失效  如果是xml就正常

**Comment by goweii** [comment]
xml也需要在代码里配置visualleffect吧，应该是一样的。你有把view添加到窗口吧？

**Comment by Xiaolangs** [comment]
> xml也需要在代码里配置visualleffect吧，应该是一样的。你有把view添加到窗口吧？

是啊  同样的布局  xml 和 代码  xml可以正常  代码就不行

**Comment by Xiaolangs** [comment]
> > xml也需要在代码里配置visualleffect吧，应该是一样的。你有把view添加到窗口吧？
> 
> 是啊 同样的布局 xml 和 代码 xml可以正常 代码就不行

**Comment by Xiaolangs** [comment]
> xml也需要在代码里配置visualleffect吧，应该是一样的。你有把view添加到窗口吧？

我当时以为是没有addview  我专门打印了 view的信息  可以确定是的存在的

**Comment by Xiaolangs** [comment]
就是我把你那个anyLayer的dialogLayer 里的子布局换成代码就失效了  阴影层正常
